#ifndef COMBOBOXDIALOG_H
#define COMBOBOXDIALOG_H

#include <QDialog>
#include <QMessageBox>  // Include QMessageBox for potential message boxes

#include "ui_combodialog.h"  // Include the UI header generated by Qt Designer

class ComboBoxDialog : public QDialog, public Ui::ComboBoxDialog {
    Q_OBJECT

public:
    explicit ComboBoxDialog(QWidget *parent = 0);
    ~ComboBoxDialog();
};

#endif  // COMBOBOXDIALOG_H
